env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  # linebreak-style:
  #   - error
  #   - windows
  #   - unix
  quotes:
    - error
    - single
    - avoidEscape: true
  semi:
    - error
    - never
  eol-last:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  no-unused-vars:
    - 2
  no-inner-declarations:
    - 2
  require-atomic-updates:
    - 2
